nodebucket:
    build: .
    command: "mix run --no-halt"
    external_links:
        - rosettahomeservices_mongodb_1:mongo
        - rosettahomeservices_influxdb_1:influx
    ports:
        - "5683:5683/udp"
    dns:
        - 172.16.24.190
        - 172.17.24.190
        - 10.6.10.208
        - 8.8.8.8
        - 8.8.4.4
    env_file:
        - .env
